### ISSUE TITLE
Question about the arquitecture

### ISSUE THREAD

**Issue by gugaiz** [shashimal/terraform-ecs#1]
I think it is an amazing job, but few questions.

Why would you put the frontend service on a public subnet? Wouldn't be better to just put it on the private subnets?
The NAT on the diagram, shouldn't be placed on the private subnets? I guess the public subnets have an internet gateway instead of a NAT gateway.

**Comment by shashimal** [comment]
Hi @gugaiz 
Thanks for the feedback and sorry for the late reply.

Yes, we can put the frontend service in the private subnet and send the traffic from the public ALB.

NAT gateway should be placed in the public subnet because containers in the private subnets should be able to connect ECR and pull images.  Refer to this for a detailed explanation. https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html

**Comment by gugaiz** [comment]
Thanks for your answer. With regards to the NAT gateway, I misunderstood the diagram and I thought you were giving access to the instances on the public network using the NAT gateway the but graph was just showing where the NAT gateway is deployed.
